#- alias: backdoor motion notification
#  id: 82f3852a-b4cf-4d7a-8d76-50b7f4b098af
#  initial_state: true
#  mode: parallel
#  trigger: 
#    - platform: state
#      entity_id: binary_sensor.person_at_back_door
#      from: 'off'
#      to: 'on'
#      variables:
#        camera_name: backdoor
#    - platform: state
#      entity_id: binary_sensor.person_at_amcrest2
#      from: 'off'
#      to: 'on'
#      variables:
#        camera_name: amcrest2
#  condition:
#    - condition: state
#      entity_id: input_boolean.suspend_camera_notifications
#      state: "off"
#    - condition: template
#      value_template:  "{{ states('input_boolean.suspend_camera_notifications_' ~ camera_name) == 'off'}}"
#  action:
#    - service: script.camera_activity_notify
#      data_template:
#        camera: "{{ camera_name }}"


#- alias: frontyard motion notification
#  id: 94876859-466d-430d-813c-e3f17e036033
#  initial_state: true
#  trigger: 
#    - platform: state
#      entity_id: binary_sensor.person_in_front_yard
#      from: 'off'
#      to: 'on'
#    - platform: state
#      entity_id: binary_sensor.vehicle_in_front_yard
#      from: 'off'
#      to: 'on'
#  action:
#    - service: image_processing.scan
#      entity_id: image_processing.deepstack_object_bi_front_yard
#    - service: script.camera_activity_notify
#      data_template:
#        message: "Front Yard Motion"
#        image: "https://hass.chiapusio.org/local/ds/{{ state_attr('image_processing.deepstack_object_bi_front_yard', 'friendly_name') }}_{{ state_attr('image_processing.deepstack_object_bi_front_yard', 'last_target_detection') }}.jpg"
#        action10: "pause10frontyard"
#        action30: "pause30frontyard"
#        camera_id: "frontyard"
#    - service: notify.living_room_tv
#      data:
#        message: "Front Yard Motion"

#- alias: reenable backdoor notifications after one hour
#  id: 4fb5695f-bf71-49ee-8dd1-da5f5d9aaf9d
#  trigger: 
#  - platform: state
#    entity_id: automation.backdoor_motion_notification
#    from: 'on'
#    to: 'off'
#    for:
#      hours: 1
#  action:
#  - service: automation.turn_on
#    entity_id: automation.backdoor_motion_notification

- alias: reenable motion notifications after six hours
  id: 7cb6b9f6-abeb-437b-aae9-5ba0711cb3b3
  trigger: 
  - platform: state
    entity_id: input_boolean.suspend_camera_notifications
    from: "off"
    to: "on"
    for:
      hours: 6
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.suspend_camera_notifications


- alias: disable back camera when door opens
  id: 28e2c714-b59c-41e4-981a-2d2390e82467
  trigger:
  - platform: state
    entity_id: binary_sensor.back_door
    from: 'off'
    to: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.suspend_camera_notifications_backdoor
    - delay:
        minutes: 10
    - service: input_boolean.turn_off
      entity_id: input_boolean.suspend_camera_notifications_backdoor
      
#- alias: frontdoor motion notification
#  id: 38f7ecca-6ad0-45ac-8b98-e3d7487d93a7
#  initial_state: true
#  trigger: 
#    - platform: state
#      entity_id: binary_sensor.person_at_front_door
#      from: 'off'
#      to: 'on'
#    - platform: state
#      entity_id: binary_sensor.animal_at_front_door
#      from: 'off'
#      to: 'on'
#    - platform: state
#      entity_id: binary_sensor.vehicle_at_front_door
#      from: 'off'
#      to: 'on'
#  condition:
#    condition: state
#    entity_id: input_boolean.suspend_camera_notifications
#    state: "off"
#  action:
#    - service: image_processing.scan
#      entity_id: image_processing.deepstack_object_front_door_main
#    - service: script.camera_activity_notify
#      data_template:
#        message: "Front Door Motion"
#        image: "https://hass.chiapusio.org/local/ds/{{ state_attr('image_processing.deepstack_object_front_door_main', 'friendly_name') }}_{{ state_attr('image_processing.deepstack_object_front_door_main', 'last_target_detection') }}.jpg"
#        action10: "pause10frontdoor"
#        action30: "pause30frontdoor"
#    - service: notify.living_room_tv
#      data:
#        message: "Front Door Motion"
#    - service: media_player.play_media
#      data_template:
#        entity_id: media_player.office_display
#        media_content_id: "http://192.168.10.22/mjpg/doorbell/video.mjpg"
#        media_content_type: image/jpg
#    - service: notify.living_room_tv
#      data:
#        message: "Front Door Motion"
#        data:
#          icon: "http://192.168.10.22/image/doorbell"
