- alias: dehumidifier froze over
  id: d27ee695-992a-47ae-b6ed-6150376c18c6
  trigger: 
    - platform: numeric_state
      entity_id: sensor.my_ecobee_humidity
      above: 56
    - platform: numeric_state
      entity_id: sensor.dehumidifier_smartenergy_metering
      below: 465
      above: 440
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.my_ecobee_humidity
        above: 56
      - condition: numeric_state
        entity_id: sensor.dehumidifier_smartenergy_metering
        below: 470
  action:
    - service: notify.mobile_app_sm_n986u
      data_template:
        message: "Turning off the humidifier. Value: {{trigger.entity_id.attributes.state}}"
#    - service: homeassistant.turn_off
#      entity_id: switch.dehumidifier_on_off
