- alias: realtime free game posts
  id: 5f2665ad-01be-48a8-bc93-4a3fc3908c55
  trigger:
    - platform: state
      entity_id: sensor.reddit_gamedeals
  condition:
    - condition: state
      entity_id: binary_sensor.new_gamedeals_free
      state: 'on'
    - condition: template
      value_template: "{{ states('sensor.last_gamedeal') != state_attr('sensor.reddit_gamedeals', 'posts')[ states('input_number.gamedeals_free_index')|int ].title }}"
  action:
    - service: notify.freebie_llama_chipsworld
      data:
        message: ""
#        target: ["961330364478001165","633522789231362067"]
        target: ["633522789231362067"]
        data:
          embed:
            title: "{{ state_attr('sensor.reddit_gamedeals', 'posts')[ states('input_number.gamedeals_free_index')|int ].title }} "
            description: "{{ state_attr('sensor.reddit_gamedeals', 'posts')[ states('input_number.gamedeals_free_index')|int ].body }}"
            url: "{{ state_attr('sensor.reddit_gamedeals', 'posts')[ states('input_number.gamedeals_free_index')|int ].url }}"
            footer: 
              text: "Score: {{ state_attr('sensor.reddit_gamedeals', 'posts')[ states('input_number.gamedeals_free_index')|int ].score }}"
#    - service: input_text.set_value
#      target:
#        entity_id: input_text.last_new_gamedeal_title
#      data:
#        value: "{{ state_attr('sensor.reddit_gamedeals', 'posts')[ states('input_number.gamedeals_free_index')|int ].title }}"
    - service: mqtt.publish
      data:
        payload_template: "{{ state_attr('sensor.reddit_gamedeals', 'posts')[ states('input_number.gamedeals_free_index')|int ].title }}"
        topic: homeassistant/sensor/last_gamedeal/name
        retain: true