- alias: gamedeals free games
  id: acf34f9b-324b-4051-bc9e-6901f45caf8f
  trigger:
    - platform: sun
      event: sunset
  condition:
    condition: state
    entity_id: binary_sensor.gamedeals_free
    state: 'on'
  action:
    - variables:
        freebies: >
          {% set ns = namespace(free=[]) %}
          {% for count in range(0, states('sensor.reddit_gamedeals_2')|int - 1) %}
            {% if ((state_attr('sensor.reddit_gamedeals_2', 'posts')[ count ].title ) is search('100%', ignorecase=True) ) %}
              {% if (state_attr('sensor.reddit_gamedeals_2', 'posts')[ count ].score > 30) %}
                {% set ns.free = ns.free + [ int(count) ] %}
              {% endif %}
            {% endif %}
          {% endfor %}
          {{ ns.free }}
    - repeat:
        count: '{{ freebies | count }}'
        sequence:
        - variables:
            item_num: '{{ freebies [repeat.index - 1 ] }}'
        - service: notify.freebie_llama_chipsworld
          data:
            message: ""
            target: [961330364478001165]
            data:
              embed:
                title: "{{ state_attr('sensor.reddit_gamedeals_2', 'posts')[ item_num ].title }}"
                description: "{{ state_attr('sensor.reddit_gamedeals_2', 'posts')[ item_num ].body }}"
                url: "{{ state_attr('sensor.reddit_gamedeals_2', 'posts')[ item_num ].url }}"

# webhook addr: https://hass.chiapusio.org/api/webhook/1c78de0f-c150-4c32-b8ec-51e10c08ddad

- alias: realtime free game posts
  id: 5f2665ad-01be-48a8-bc93-4a3fc3908c55
  trigger:
    - platform: state
      entity_id: sensor.reddit_gamedeals
  condition:
    condition: state
    entity_id: binary_sensor.new_gamedeals_free
    state: 'on'
  action:
    - service: notify.freebie_llama_chipsworld
      data:
        message: ""
        target: [961330364478001165]
        data:
          embed:
            title: "{{ state_attr('sensor.reddit_gamedeals', 'posts')[ (states('input_number.gamedeals_free_index')|int) ].title }}"
            description: "{{ state_attr('sensor.reddit_gamedeals', 'posts')[ (states('input_number.gamedeals_free_index')|int) ].body }}"
            url: "{{ state_attr('sensor.reddit_gamedeals', 'posts')[ (states('input_number.gamedeals_free_index')|int) ].url }}"
            footer: "Score: {{ state_attr('sensor.reddit_gamedeals', 'score')[ (states('input_number.gamedeals_free_index')|int) ].url }}"