- alias: born in a barn (backdoor)
  id: fc3a9f22-59bd-41e7-af8e-1124f48162f5
  trigger:
    platform: state
    entity_id: binary_sensor.back_door
    to: 'on'
    for:
      minutes: 5
  action:
    service: notify.mobile_app_sm_n986u
    data:
      message: "the back door was left open"