- alias: take out recycling bin
  id: b30798c5-ba5c-4322-900a-64cc1fc35f7e
  trigger:
    platform: time
    at: "18:00:00"
  condition:   
  - condition: numeric_state
    entity_id: sensor.recycling
    attribute: days
    below: 2
  action:
    service: notify.mobile_app_sm_n986u
    data:
      message: "Take out Recycling bin tonight"

- alias: Turn on lights for maids
  id: 44bce5d9-e0e0-447b-850f-93e080ea0b9f
  trigger:
    - platform: time_pattern
      minutes: '/5'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.living_room
        state: 'off'
      - condition: template
        value_template: "{{ ((as_timestamp(states.calendar.maids_today.attributes.start_time) - as_timestamp(now())) < 1800) and ((as_timestamp(states.calendar.maids_today.attributes.start_time) - as_timestamp(now())) > 0)  }}"
  action:
    - service: scene.turn_on
      entity_id: scene.housecleaners_coming
    - service: notify.mobile_app_sm_n986u
      data:
        message: "Prepare the house for the Maids"