- alias: take out recycling bin
  trigger:
    platform: time
    at: "18:00:00"
  condition:   
  - condition: template
    value_template: '{{ states.sensor.recycling.attributes.days == 1 }}'
  action:
    service: notify.mobile_app_sm_n986u
    data:
      message: "Take out Recycling bin tonight"

- alias: Turn on lights for maids
  trigger:
    - platform: time_pattern
      minutes: '/5'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.living_room
        state: 'off'
      - condition: template
        value_template: "{{ ((as_timestamp(states.calendar.maids_today.attributes.start_time) - as_timestamp(now())) < 1800) and ((as_timestamp(states.calendar.maids_today.attributes.start_time) - as_timestamp(now())) > 0)  }}"
  action:
    - service: scene.turn_on
      entity_id: scene.housecleaners_coming
    - service: notify.mobile_app_sm_n986u
      data:
        message: "Prepare the house for the Maids"