- alias: take out recycling bin
  trigger:
    platform: time
    at: "18:00:00"
  condition:   
  - condition: template
    value_template: '{{ states.sensor.recycling.attributes.days == 1 }}'
  action:
    service: notify.notify_chip
    data:
      message: "Take out Recycling bin tonight"

- alias: Turn on lights for maids
  trigger:
    platform: time
    at: '09:00:00'
    condition:
    - condition: template
      value_template: "{{  ((as_timestamp(states.calendar.starbucks_today.attributes.start_time) - as_timestamp(now())) < 14400) and ((as_timestamp(states.calendar.maids_today.attributes.start_time) - as_timestamp(now())) > 0)  }}"
  action:
    - service: scene.turn_on
      entity_id: scene.all_indoor_lights_on