- alias: take out recycling bin
  trigger:
    platform: time
    at: "18:00:00"
  condition:   
  - condition: template
    value_template: '{{ states.sensor.recycling.attributes.days == 1 }}'
  action:
    service: notify.notify_chip
    data:
      message: "Take out Recycling bin tonight"