- alias: front yard scene
  trigger:
    platform: sun
    event: sunset
    offset: "00:00:00"
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: 'input_select.outdoor_light_scene'
        state: 'Normal'
      - condition: state
        entity_id: 'input_select.outdoor_light_scene'
        state: 'Halloween'
      - condition: state
        entity_id: 'input_select.outdoor_light_scene'
        state: 'Christmas'
      - condition: state
        entity_id: 'input_select.outdoor_light_scene'
        state: 'St Patricks'
      - condition: state
        entity_id: 'input_select.outdoor_light_scene'
        state: 'Independence Day'
      - condition: state
        entity_id: 'input_select.outdoor_light_scene'
        state: 'Memorial Day'
      - condition: state
        entity_id: 'input_select.outdoor_light_scene'
        state: 'Green Bay Packers'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {% if is_state( "input_select.outdoor_light_scene", "Normal" ) %}
            scene.yard_light_normal
          {% elif is_state( "input_select.outdoor_light_scene", "Halloween" ) %}
            scene.yard_light_halloween
          {% elif is_state( "input_select.outdoor_light_scene", "Christmas" ) %}
            scene.yard_light_christmas
          {% elif is_state( "input_select.outdoor_light_scene", "St Patricks" ) %}
            scene.yard_light_stpatricks
          {% elif is_state( "input_select.outdoor_light_scene", "Independence Day" ) %}
            scene.yard_light_independence
          {% elif is_state( "input_select.outdoor_light_scene", "Memorial Day" ) %}
            scene.yard_light_independence
          {% elif is_state( "input_select.outdoor_light_scene", "Green Bay Packers" ) %}
            scene.yard_light_greenbay
          {% endif %}

- alias: floods_off_at_dawn
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:00:00"
  action:
    - service: light.turn_off
      entity_id: light.flood01
    - service: light.turn_off
      entity_id: light.flood02

- alias: turn off house floods at midnight
  trigger:
    platform: time
    at: "00:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id: light.flood03
    - service: homeassistant.turn_off
      entity_id: light.flood04