- alias: turn off house floods at midnight
  trigger:
    platform: time
    at: "00:00:00"
  condition:
    - condition: state
      entity_id: input_select.outdoor_light_scene
      state: 'Christmas'
  action:
    - service: homeassistant.turn_off
      entity_id: light.flood03
    - service: homeassistant.turn_off
      entity_id: light.flood04