- alias: turn off indoor christmas lights in the morning
  id: 8d2aacf8-6244-4fdf-b16b-61e7709439a1
  trigger:
    platform: time
    at: "00:09:00"
  condition:
    - condition: state
      entity_id: input_select.outdoor_light_scene
      state: 'Christmas'
  action:
    - service: switch.turn_on
      entity_id: switch.ewelink_sa_003_zigbee_on_off

- alias: turn off indoor christmas lights at midnight
  id: 2f619fa2-30dc-446a-b1ca-d6f6325bcd89
  trigger:
    platform: time
    at: "00:00:00"
  condition:
    - condition: state
      entity_id: input_select.outdoor_light_scene
      state: 'Christmas'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.ewelink_sa_003_zigbee_on_off
