- alias: Washer finished notification
  id: bc778f63-3ff8-4486-9adb-39effc0dd76c
  trigger: 
    - platform: state
      entity_id: binary_sensor.washer_running
      to: 'off'
      for:
        minutes: 6
  action:
    - service: notify.mobile_app_sm_n986u
      data_template:
        message: "The washer is done"

- alias: Dryer finished notification
  id: 27c1fec7-0631-4569-974c-7ed54093a0d2
  trigger:
    - platform: state
      entity_id: binary_sensor.dryer_vibration
      to: 'off'
      for:
        minutes: 5
  action:
    - service: notify.mobile_app_sm_n986u
      data_template:
        message: "The dryer is done"