- alias: Washer finished notification
  id: bc778f63-3ff8-4486-9adb-39effc0dd76c
  trigger: 
    - platform: state
      entity_id: binary_sensor.washer_running
      to: 'off'
      for:
        minutes: 6
  action:
    - service: notify.mobile_app_sm_n986u
      data_template:
        message: "The washer is done"
