##
## Turn off lights at midnight if the TV is off
##
- alias: turn off living room lights at midnight
  id: 277b1ae2-1b04-4656-8d6c-ce23f7c84ab4
  trigger:
    platform: time
    at: "23:00:00"
  condition:
    condition: state
    entity_id: media_player.lg_webos_smart_tv
    state:  'off'
  action:
    service: scene.turn_on
    entity_id: scene.good_night_lights

##
## Turn off Lights if TV turns off after midnight
##
- alias: turn off lights when done watching TV
  id: 9608670a-5061-44ca-9827-239f19ba9b23
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: time
        after: "23:00:00"
        before: "05:00:00"
      - condition: state
        entity_id: sun.sun 
        state: below_horizon
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_dim
    - service: scene.turn_on
      entity_id: scene.dining_room_dim
    - service: switch.turn_off
      entity_id: switch.curio_cabinet_lamp
    - service: timer.start
      data:
        entity_id: timer.5m

- alias: turn off living room lights after timer
  id: 8767441e-27d8-4d10-a652-6651c84041d7
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.5m
  action:
    service: scene.turn_on
    entity_id: scene.good_night_lights

##
## Turn on lights at sunset
##

- alias: turn on living room lights at sunset
  id: 70d19e4a-2360-48ad-8abc-a0fa12df379c
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 15
  condition:
    condition: template
    value_template: '{{ is_state_attr("sun.sun", "rising", false) }}'
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - switch.curio_cabinets
        - switch.hutch_light
        - switch.curio_cabinet_lamp
    - service: scene.turn_on
      entity_id: scene.livingroom_normal
    - service: scene.turn_on
      entity_id: scene.dining_room_normal


- alias: turn on living room lights early if cloudy
  id: dd5e6b30-7222-48f5-8035-c4df9b10aba6
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 40
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        above: 40
      - condition: template
        value_template: '{{ is_state_attr("sun.sun", "rising", false) }}'
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_normal
    - service: scene.turn_on
      entity_id: scene.dining_room_normal
    - service: homeassistant.turn_on
      entity_id: 
        - switch.hutch_light
        - switch.curio_cabinet_lamp
        - switch.curio_cabinets

- alias: turn on living room lights even earlier if 100% cloudy
  id: 87592801-4bc6-4fde-9515-63df8dc1046b
  trigger:
    platform: numeric_state
    entity_id: sensor.dark_sky_cloud_coverage
    above: 85
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 40 }}'
      - condition: template
        value_template: '{{ is_state_attr("sun.sun", "rising", false) }}'
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_normal
    - service: scene.turn_on
      entity_id: scene.dining_room_normal
    - service: homeassistant.turn_on
      entity_id: 
        - switch.hutch_light
        - switch.curio_cabinet_lamp
        - switch.curio_cabinets

- alias: turn on living room lights when there is an afternoon storm
  id: 3ce0ab6b-6b27-464e-b227-340c6f84978b
  trigger:
    platform: numeric_state
    entity_id: sensor.dark_sky_precip_intensity
    above: 0.6
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.dark_sky_precip_probability
        above: 80
      - condition: template
        value_template: '{{ is_state_attr("sun.sun", "rising", false) }}'
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_normal
    - service: scene.turn_on
      entity_id: scene.dining_room_normal
    - service: homeassistant.turn_on
      entity_id: 
        - switch.hutch_light
        - switch.curio_cabinet_lamp

- alias: Media player paused/stopped
  id: b239b22a-5bae-4e71-b7cc-99f7c6fecfb2
  trigger:
    - platform: state
      entity_id: media_player.living_room_shield, media_player.plex_plex_for_lg_lg_75sm8670pua
      from: playing
#      to: idle
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal

- alias: Media player playing
  id: b99dc5b6-0243-4407-86df-1eecc1a00ad3
  trigger:
    - platform: state
      entity_id: media_player.living_room_shield
      to: playing
#      from: idle
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_dim

- alias: Packers Playing
  id: 76271bea-d291-4264-81bc-9fe2fcde508d
  trigger:   
  - platform: state
    entity_id: calendar.green_bay_packers
    to: "on"
  action:
    service: scene.turn_on
    entity_id: scene.packers_playing

- alias: Packers done Playing
  id: 6404c369-15d4-4450-b6e1-9d114c135482
  trigger:   
  - platform: state
    entity_id: calendar.green_bay_packers
    to: "off"
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal

- alias: Tori scheduled for work this morning
  id: ab5c5a72-3831-44d1-a860-3fc9b23168c5
  trigger:
    - platform: time_pattern
      minutes: '/5'
  condition:
    condition: and
    conditions:
      - condition: time
        after: "04:30:00"
        before: "09:00:00"
      - condition: template
        value_template: "{{ ((as_timestamp(states.calendar.work_today.attributes.start_time) - as_timestamp(now())) < 2700) and ((as_timestamp(states.calendar.waterbean_today.attributes.start_time) - as_timestamp(now())) > 0)  }}"
      - condition: state
        entity_id: person.tori
        state: home
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 15 }}'
      - condition: state
        entity_id: switch.hutch_light
        state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_dim
    - service: switch.turn_on
      entity_id: switch.hutch_light

- alias: Tori left for work
  id: 7c8d4f4c-d3f2-426e-a321-c0ea3175bee2
  trigger:
    - platform: state
      entity_id: person.tori
      from: home
  condition:
    - condition: time
      after: '04:30:00'
      before: '09:00:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.hutch_light
      - light.living_room_lamp_1
      - light.living_room_lamp_2
      - light.foyer_lamp

- alias: turn on candle in the morning
  id: 8d184c18-380b-4d4a-9528-460badcd25d9
  trigger:
    platform: time
    at: "09:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.candle_light
    - service: light.turn_on
      entity_id: light.crystal_castle_1
      data:
        brightness: 40

# turn on hyperion wled lights when TV turns on
#
- alias: turn on ambilight when TV turns on
  id: 03e16f89-e328-4051-93e4-f7f6fc96003a
  trigger:
    platform: state
    entity_id: media_player.lg_webos_smart_tv
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lg75_wled
        brightness: 255