- alias: Tori arriving Home
  id: 29af254f-05f1-4c72-9e88-0c704ca1ef12
  trigger:
    platform: state
    entity_id: person.tori
    to: home
  action:
    - service: scene.create
      data:
        scene_id: tori_is_home_save
        snapshot_entities:
        - light.wled
    - service: scene.turn_on
      entity_id: scene.triumphant_return
    - delay:
        seconds: 10
    - service: scene.turn_on
      entity_id: scene.tori_is_home_save
    
- alias: Notify when someone enters or leaves a zone
  id: ef70f12c-3fb3-4146-af59-16a299c1f43a
  description: ''
  trigger:
    platform: state
    entity_id: person.tori
  condition:
    condition: template
    value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: notify.mobile_app_sm_n986u
      data_template:
        title: 'Location update {{ states.sensor.time.state }}'
        message: "{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state == 'not_home' %}has left {{ trigger.from_state.state }}{% endif %}{% if trigger.from_state.state == 'not_home' %}arrived at {{ trigger.to_state.state }}{% endif %}"
#    - service: notify.living_room_tv
#      data_template:
#        title: 'Location update {{ states.sensor.time.state }}'
#        message: "{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state == 'not_home' %}has left {{ trigger.from_state.state }}{% endif %}{% if trigger.from_state.state == 'not_home' %}arrived at {{ trigger.to_state.state }}{% endif %}"
      
- alias: Cindy arriving Home
  id: 3a1e5e64-2659-4a67-9fac-d3b9801b6a7c
  trigger:
    platform: state
    entity_id: person.cindy
    to: home
  action:
    - service: scene.create
      data:
        scene_id: office_save
        snapshot_entities:
        - light.wled
        - light.office_lamp
    - service: scene.turn_on
      entity_id: scene.triumphant_return
    - service: timer.start
      data:
        entity_id: timer.alert
    - service: notify.living_room_tv
      data:
        message: "Cindy is home"

- alias: turn off triumphant return
  id: a489b413-834c-4253-8d61-ceb1d4371584
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.alert
  action:
    service: scene.turn_on
    data:
      entity_id: scene.office_save

