- alias: Tori Leaving Home
  trigger:
    platform: state
    entity_id: person.tori
    from: home
  action:
    - service: light.turn_off
      entity_id: 
        - light.desk_lamp
        - light.dresser_lamp
      
- alias: Tori arriving Home
  trigger:
    platform: state
    entity_id: person.tori
    to: home
  action:
    - service: scene.create
      data:
        scene_id: tori_is_home_save
        snapshot_entities:
        - light.wled
    - service: scene.turn_on
      entity_id: scene.triumphant_return
    - delay:
        seconds: 10
    - service: scene.turn_on
      entity_id: scene.tori_is_home_save
    - service: light.turn_on
      entity_id: 
        - light.desk_lamp
        - light.dresser_lamp
    
- alias: Notify when someone enters or leaves a zone
  description: ''
  trigger:
    platform: state
    entity_id: person.tori
  condition:
    condition: template
    value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service: notify.mobile_app_sm_n986u
      data_template:
        title: 'Location update {{ states.sensor.time.state }}'
        message: "{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state == 'not_home' %}has left {{ trigger.from_state.state }}{% endif %}{% if trigger.from_state.state == 'not_home' %}arrived at {{ trigger.to_state.state }}{% endif %}"
    - service: notify.mobile_app_sm_n950u
      data_template:
        title: 'Location update {{ states.sensor.time.state }}'
        message: "{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state == 'not_home' %}has left {{ trigger.from_state.state }}{% endif %}{% if trigger.from_state.state == 'not_home' %}arrived at {{ trigger.to_state.state }}{% endif %}"
    - service: notify.living_room_tv
      data_template:
        title: 'Location update {{ states.sensor.time.state }}'
        message: "{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state == 'not_home' %}has left {{ trigger.from_state.state }}{% endif %}{% if trigger.from_state.state == 'not_home' %}arrived at {{ trigger.to_state.state }}{% endif %}"
      
- alias: Cindy arriving Home
  trigger:
    platform: state
    entity_id: person.cindy
    to: home
  action:
    - service: scene.create
      data:
        scene_id: office_save
        snapshot_entities:
        - light.wled
        - light.office_lamp
    - service: scene.turn_on
      entity_id: scene.triumphant_return
    - service: timer.start
      data:
        entity_id: timer.alert
    - service: notify.lg_webos_smart_tv
      data:
        message: "Cindy is home"

- alias: turn off triumphant return
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.alert
  action:
    service: scene.turn_on
    data:
      entity_id: scene.office_save


- alias: Tori arriving Home late
  trigger:
    platform: state
    entity_id: person.tori
    to: home
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state:  below_horizon
    - condition: state
      entity_id: light.living_room
      state:  'off'
  action:
    - service: scene.turn_on
      entity_id: scene.livingroom_dim
    - service: switch.turn_on
      entity_id: switch.hutch_light
    - service: timer.start
      data:
        entity_id: timer.late_tori

- alias: turn off lights after tori as gotten home late
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.late_tori
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.living_room
    - service: switch.turn_off
      entity_id: switch.hutch_light
