- alias: "Update USPS Mail Camera"
  trigger:
    - platform: state
      entity_id: sensor.mail_usps_mail
  action:
    - service: local_file.update_file_path
      data_template:
        entity_id: camera.mail_usps
        file_path: >
          {% if state_attr('sensor.mail_usps_mail','image') == None  %}
          /config/custom_components/mail_and_packages/mail_none.gif
          {% else %}
          /config/www/mail_and_packages/{{ state_attr('sensor.mail_usps_mail','image') }}
          {% endif %}
- alias: "Mail Notif - Mail Delieveries"
  initial_state: 'on'
  trigger:
  #Trigger if mail or packages get updated
    - platform: state
      entity_id: sensor.mail_usps_mail
    - platform: state
      entity_id: sensor.mail_usps_delivering
  #send only if mail or packages are more than 0
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ ((as_timestamp(now()) - as_timestamp(states.sensor.mail_usps_mail.last_changed)) < 15 and sensor.mail_usps_mail > 0) }}"
        - condition: template
          value_template: "{{ ((as_timestamp(now()) - as_timestamp(states.sensor.mail_packages_in_transit.last_changed)) < 15 and sensor.mail_packages_in_transit > 0) }}"
  action:
    - service: notify.notify_chip
      data_template:
        title: "*Today's Mail and Packages*"
        message: "{{ states('sensor.mail_deliveries_message')}}"
    - service: notify.notify_chip
      data:
        message: "Here is the mail"
        data:
          document:
            file: "/config/www/mail_and_packages/mail_today.gif"