- alias: set initial state for Eddies mister
  id: 129aa50c-f2fd-4b62-85e9-33ae2c8313a9
  trigger:
    platform: homeassistant
    event: start
  action:
    - delay: '00:00:30'
    - service: homeassistant.turn_off
      entity_id: switch.eddies_mister

- alias: Sync Tasmota states
  id: b9b8a397-1c0d-4077-a2c9-dad8e5abb9e0
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
  # sync state for pre8.2 autodiscovery devices
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/backlog
      payload: 'setoption19 1;Fade ON;Speed 5; state'

 # automations.yaml file
- id: shellies_announce
  alias: 64b84f07-ba00-48bd-9999-1194261d137e
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/1"  # Modifying this if you are using Shelly Motion can drain your device's battery quickly.
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce

- id: 'shellies_discovery'
  alias: 1326abd3-1aac-4f5c-baf3-d26b86ffbfce
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'