- alias: set initial state for Eddies mister
  trigger:
    platform: homeassistant
    event: start
  action:
    - delay: '00:00:30'
    - service: homeassistant.turn_off
      entity_id: switch.eddies_mister