- alias: turn on deck floodlights at sunset
  id: d50b3dbe-d917-4aec-8bb9-6b1c4a8d98d9
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -3
    - platform: state
      entity_id: binary_sensor.shelly_2_5_e8db84d2729c_input_1
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.shelly_2_5_e8db84d2729c_input_1
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
  action:
    - service: homeassistant.turn_on
      entity_id: switch.shelly_2_5_e8db84d2729c_relay_1

- alias: turn on front porch lights 
  id: 9eb378bd-b231-4edf-b857-8a070d08d145
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -3
    - platform: state
      entity_id: binary_sensor.shelly_2_5_8caab55f9707_input_0
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.shelly_2_5_8caab55f9707_input_0
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: state
        entity_id: input_select.porch_light_setting
        state: 'always on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.shelly_2_5_8caab55f9707_relay_0
    
- alias: turn front driveway floods
  id: 7498deb5-bef0-4f96-a5c2-30a9939ba3af
  trigger: 
    - platform: state
      entity_id: binary_sensor.shelly_2_5_8caab55f9707_input_1
      to: 'on'
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -3
    - platform: numeric_state
      entity_id: sensor.shelly_2_5_8caab55f9707_power_1
      below: 10
      for: "00:05:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.shelly_2_5_8caab55f9707_input_1
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: state
        entity_id: input_select.front_flood_setting
        state: 'always on'
  action:
    - service: homeassistant.turn_on
      target:
        entity_id: switch.shelly_2_5_8caab55f9707_relay_1
    - service: homeassistant.turn_off
      target:
        entity_id: switch.shelly_2_5_8caab55f9707_relay_1
    - delay: 00:00:02
    - service: homeassistant.turn_on
      target:
        entity_id: switch.shelly_2_5_8caab55f9707_relay_1
  
- alias: turn back driveway floods
  id: e6ffac97-3bcf-483c-b91c-754ac733f26c
  trigger: 
    - platform: state
      entity_id: binary_sensor.shelly_2_5_e8db84d2729c_input_0
      to: 'on'
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: -3
    - platform: numeric_state
      entity_id: sensor.shelly_2_5_e8db84d2729c_power_0
      below: 10
      for: "00:05:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.shelly_2_5_e8db84d2729c_input_0
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: below_horizon
  action:
    - service: homeassistant.turn_on
      target:
        entity_id: switch.shelly_2_5_e8db84d2729c_relay_0
    - service: homeassistant.turn_off
      target:
        entity_id: switch.shelly_2_5_e8db84d2729c_relay_0
    - delay: 00:00:02
    - service: homeassistant.turn_on
      target:
        entity_id: switch.shelly_2_5_e8db84d2729c_relay_0
