- alias: limit PS4 time
  id: 2b8f4427-1fca-46b9-87f4-07472c29e1aa
  trigger:
  - platform: time_pattern
    minutes: "/5"
    seconds: 04
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: media_player.playstation_4
      state: 'playing'
    - condition: template
      value_template: '{{ states("sensor.playstation_game_time_today") |float > 2.1 }}'
  action:
    - service: notify.mobile_app_sm_n986u
      data:
        message: "PS4 2h time limit reached"