- alias: Margo is here
  trigger:
    platform: state
    entity_id: device_tracker.galaxy_note10
    to: home
  action:
    service: tts.google_say
    entity_id: "all"
    data:
      message: "Alert, Margo is here"

- alias: Tommy is here
  trigger:
    platform: state
    entity_id: device_tracker.galaxy_note10
    to: home
  action:
    service: tts.google_say
    entity_id: "all"
    data:
      message: "Alert, Tommy is here"

- alias: Natalie is here
  trigger:
    platform: state
    entity_id: device_tracker.natalies_iphone
    to: home
  action:
    service: tts.google_say
    entity_id: media_player.office_display
    data:
      message: "Alert, Natalie is here"

- alias: Suspend camera notifications when Chip comes home
  trigger:
    platform: state
    entity_id: person.chip
    to: home
  action:
    - service: automation.turn_off
      entity_id: automation.frontyard_motion_notification
    - service: automation.turn_off
      entity_id: automation.backdoor_motion_notification
    - delay:
        minutes: 10
    - service: automation.turn_on
      entity_id: automation.frontyard_motion_notification
    - service: automation.turn_on
      entity_id: automation.backdoor_motion_notification
      
- alias: suspend frontyard camera notifications when jeep-wled
  trigger:
    platform: state
    entity_id: device_tracker.wled_jeep
    to: home
  action:
    - service: automation.turn_off
      entity_id: automation.frontyard_motion_notification
    - delay:
        minutes: 10
    - service: automation.turn_on
      entity_id: automation.frontyard_motion_notification