- alias: Suspend camera notifications when Chip comes home
  id: 73f5932d-2ad6-45b5-b96d-6e5ec506124a
  trigger:
    platform: state
    entity_id: person.chip
    to: home
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.suspend_camera_notifications
    - delay:
        minutes: 10
    - service: input_boolean.turn_off
      entity_id: input_boolean.suspend_camera_notifications
      
- alias: suspend frontyard camera notifications when jeep-wled
  id: bdc0a8d7-71e2-4986-b652-9192045efdb5
  trigger:
    platform: state
    entity_id: device_tracker.wled_jeep
    to: home
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.suspend_camera_notifications
    - delay:
        minutes: 10
    - service: input_boolean.turn_off
      entity_id: input_boolean.suspend_camera_notifications