- alias: cycle mister
  id: 43359d56-d56a-460e-9c4e-196c349e1d30
  trigger:
    - platform: time_pattern
      minutes: '/10'
  action:
    service: switch.turn_on
    entity_id: switch.eddies_mister

- alias: turn off mister
  id: ee3d8bea-8cf0-4a29-8ea3-76217dc81873
  trigger:
   - platform: state
     entity_id: switch.eddies_mister
     from: 'off'
     to: 'on'
     for:
       minutes: 1
  action:
    service: homeassistant.turn_off
    entity_id: switch.eddies_mister
