# Example automations.yaml entry
- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "tasmotas/cmnd/state"
        payload: ""
    - service: mqtt.publish
      data:
        topic: tasmotas/cmnd/POWER
    - service: mqtt.publish
      data:
        topic: tasmotas/cmnd/POWER2
    - service: mqtt.publish
      data:
        topic: tasmotas/cmnd/POWER3
