- alias: brrrrrrrrrr
  trigger:
    platform: time
    at: "07:00:00"
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states('sensor.my_ecobee_temperature')|int < 60 }}"
      - condition: template
        value_template: "{{ states('sensor.dark_sky_temperature')|int < 50 }}"
#      - condition: template
#        entity_id: climate.my_ecobee
#        valute_template: '{{ state.attributes.hvac_modes }}'
#        state:  'Cool'
  action:
    - service: notify.mobile_app_sm_n986u
      data:
        message: "I could have turned the heat on for you"

- alias: Im still cold
  trigger:
  - platform: state
    entity_id: climate.my_ecobee
    from:  'heat'
    to:  'cool'
  condition: 
    - condition: time
      after: "09:00:00"
      before: "23:00:00"
  action:
    - service: scene.create
      data:
        scene_id: cold_case_save
        snapshot_entities:
        - light.wled
        - light.office_lamp
        - light.dining_room_lamp_east
        - light.dining_room_lamp_west
        - light.living_room_lamp_1
        - light.living_room_lamp_2
        - light.foyer_lamp
    - service: scene.turn_on
      entity_id: scene.cold_case
    - delay:
        seconds: 10
    - service: scene.turn_on
      entity_id: scene.cold_case_save

- alias: Things are Warming Up
  trigger:
  - platform: state
    entity_id: climate.my_ecobee
    from:  'cool'
    to:  'heat'
  condition: 
    - condition: time
      after: "09:00:00"
      before: "23:00:00"
  action:
    - service: scene.create
      data:
        scene_id: warm_up_save
        snapshot_entities:
        - light.wled
        - light.office_lamp
        - light.dining_room_lamp_east
        - light.dining_room_lamp_west
        - light.living_room_lamp_1
        - light.living_room_lamp_2
        - light.foyer_lamp
    - service: scene.turn_on
      entity_id: scene.warm_up
    - delay:
        seconds: 10
    - service: scene.turn_on
      entity_id: scene.warm_up_save