- alias: Sync tasmota configuration
  id: f3035d6b-8859-404e-abf5-3801ad9efd14
  initial_state: false
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/backlog
      payload: 'Fade ON;Speed 5; OtaUrl http://ota.tasmota.com/tasmota/release-10.1.0/tasmota.bin.gz; so19 0; so8 1;so56 1;so57 1'
#     setOption8 show temp in fahrenheight
#     setOption19 disable homeassistant MQTT autoconf (enable tasmota autoconf)
#     setOption56 wifi network scan for strongest signal on restart
#     setOption57 wifi network re-scan for stronger signal every 44 minutes

- alias: Upgrade all tasmota devices
  id: 702a8d74-831b-47e4-a496-825838040240
  initial_state: false
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/upgrade
      payload: '1'