- alias: manage toris lights
  trigger:
    - platform: state
      entity_id: switch.gecko
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.desk_lamp
      from: 'off'
      to: 'on'
  condition: 
    condition: state
    entity_id: device_tracker.toris_iphone
    state: 'away'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.gecko
    - service: homeassistant.turn_off
      entity_id: light.desk_lamp
   
- alias: tori wake up light
  trigger:
    - platform: time
      at: "08:00:00"
  condition:
    condition: state
    entity_id: person.tori
    state: home
  action:
    service: light.turn_on
    data:
      entity_id: light.desk_lamp
      brightness: 255