- alias: manage toris lights
  trigger:
    - platform: state
      entity_id: switch.gecko
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.desk_lamp
      from: 'off'
      to: 'on'
  condition: 
    condition: state
    entity_id: device_tracker.toris_iphone
    state: 'away'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.gecko
    - service: homeassistant.turn_off
      entity_id: light.desk_lamp
   