- id: '1669869688757'
  alias: crystal wall switch control
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e2001_e2002.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.crystal_wall_switch_action
      helper_last_controller_event: input_text.crystal_wall_switch_last_event
      action_button_up_short:
      - device_id: f43ec119cb124f3aa18f6de5e3dfaf3f
        domain: light
        entity_id: light.crystal_wall
        type: brightness_increase
      action_button_up_long: []
      action_button_down_short:
      - device_id: f43ec119cb124f3aa18f6de5e3dfaf3f
        domain: light
        entity_id: light.crystal_wall
        type: brightness_decrease
      button_up_double_press: true
      button_down_double_press: true
- id: '1673987869852'
  alias: Unavailable entity detection
  description: ''
  use_blueprint:
    path: gmlupatelli/unavailable_entities_notification.yaml
    input:
      actions:
      - service: notify.chip_email
        data:
          message: '{{entities}}'
          title: Unavailable Entities
