- id: '1736353769411'
  alias: button test
  description: ''
  triggers:
  - domain: mqtt
    device_id: bd17d5ab66306df0c2f795f67b0fe710
    type: action
    subtype: single
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.office_dim
  mode: single
