####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

# https://home-assistant.io/docs/configuration/basic/
homeassistant:
  # Packages
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config/faces/
    - /config/www/
    - /config/tmp/snapshots/
  auth_providers:
   - type: trusted_networks
     trusted_networks:
       - 172.17.0.0/16
       - 192.168.10.0/24
   - type: homeassistant
  customize:
    person.chip:
      entity_picture: !secret profile_photo_chip
    person.cindy:
      entity_picture: !secret profile_photo_cindy
    person.tori:
      entity_picture: !secret profile_photo_tori
    binary_sensor.front_door:
      friendly_name: Front Door
    binary_sensor.back_door:
      friendly_name: Back Door


####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

# https://home-assistant.io/components/config/
config:
#default_config:

# https://www.home-assistant.io/integrations/zeroconf
zeroconf:

#https://www.home-assistant.io/integrations/ssdp/
ssdp:

# https://www.home-assistant.io/integrations/my/
my:

#https://www.home-assistant.io/docs/energy/
energy:

#https://www.home-assistant.io/integrations/go2rtc/
go2rtc:
  url: http://192.168.10.4:1984

#https://www.home-assistant.io/integrations/homeassistant_alerts
homeassistant_alerts:

# https://home-assistant.io/components/history/
history:

# https://www.home-assistant.io/integrations/recorder/
recorder:
  db_url: !secret hass_db_string
  purge_keep_days: 15
  commit_interval: 5
  exclude:
    domains:
      - media_player
      - device_tracker
      - automation
      - updater
    entities:
      - sun.sun
    entity_globs:
      - sensor.weather_*
    event_types:
      - call_service
  include:
    domains:
      - switch
      - light
      - sensor
      - binary_sensor
      - calendar
      - person
      - climate
    entities:
      - device_tracker.sm_s908u_2 # Cindys S22 Ultra
      - media_player.living_room_shield
      - media_player.living_room_tv
      - media_player.toris_bedroom_tv
      - media_player.mbr_shield
      - media_player.master_bedroom_tv
      - device_tracker.sm_s928u # HA App
      - device_tracker.wled_jeep # unifi
      - input_boolean.preparing_for_bedtime
      - input_boolean.evening_lights

# https://home-assistant.io/components/http/
http:
  ip_ban_enabled: false
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/24
    - 192.168.10.0/24

# https://home-assistant.io/components/logger/
logger:
  default: info
  logs:
    homeassistant.components.notify: debug
#    homeassistant.components.google_assistant: debug
#    homeassistant.core: debug
#    homeassistant.components.mqtt: debug
#    aiounifi: debug
#    homeassistant.components.unifi: debug
#    homeassistant.components.device_tracker.unifi: debug
#    homeassistant.components.switch.unifi: debug

# https://www.home-assistant.io/integrations/manual
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: '1234'

# https://home-assistant.io/components/sun/
sun:

# https://www.home-assistant.io/components/system_health/
system_health:

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

# https://home-assistant.io/docs/configuration/splitting_configuration/
zone: !include includes/zones.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
script: !include_dir_merge_list scripts
automation manual: !include_dir_merge_list includes/automation
automation ui: !include automations.yaml
scene: !include_dir_merge_list includes/scene
notify: !include notification.yaml
light: !include lights.yaml
sensor: !include_dir_merge_list includes/sensors
rest_command: !include_dir_merge_list rest_command
binary_sensor: !include binary_sensor.yaml
media_player: !include media_player.yaml
person: !include includes/person.yaml
#switch: !include includes/switch.yaml
input_select: !include includes/inputs/input_select.yaml
input_number: !include includes/inputs/input_number.yaml
#input_boolean: !include includes/inputs/input_boolean.yaml
input_text: !include includes/inputs/input_text.yaml
#image_processing: !include image_processing.yaml
template: !include templates.yaml
alert: !include includes/alerts.yaml
#https://www.home-assistant.io/components/mqtt/
mqtt: !include mqtt.yaml
#modbus: !include modbus.yaml

# https://www.home-assistant.io/integrations/stream
stream:

# https://www.home-assistant.io/integrations/media_source/
media_source:

# https://www.home-assistant.io/integrations/camera/
camera: !include camera.yaml

# https://www.home-assistant.io/integrations/frontend/
frontend: 
#  javascript_version: latest
  themes: !include_dir_merge_named themes

# https://www.home-assistant.io/integrations/cloud/
cloud:

# https://www.home-assistant.io/integrations/backup/
backup:

# https://www.home-assistant.io/integrations/bluetooth/
bluetooth:


# https://www.home-assistant.io/integrations/google_assistant/
google_assistant:
  project_id: home-assistant-integrati-72eed
  service_account: !include home-assistant-integrati-72eed-e13ed1e9b9c9.json
#  api_key: !secret google_assistant_api
  report_state: true
  exposed_domains:
    - switch
    - light
    - cover
    - group
    - scene
    - script
  expose_by_default: true
  
# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# https://www.home-assistant.io/integrations/python_script
python_script:

# Text to speech
# https://www.home-assistant.io/components/tts/  
#tts:
#  - platform: google_translate
#    service_name: google_say
#    cache: true
#    cache_dir: /tmp/tts
#    time_memory: 300


timer:
  alert:
    name: Alert
    duration: '00:00:10'
  5m:
    name: five minute timer for turning off lights at night
    duration: '00:05:00'

####################################################
#                                                  #
#                   SPEETEST                       #
#                                                  #
####################################################

# https://www.home-assistant.io/integrations/weather.darksky/
weather:

# https://github.com/alexander0042/pirate-weather-ha
# https://pirateweather.net/
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    # Additional optional values:
    latitude: !secret home_lat
    longitude: !secret home_long
#   mode: "hourly" (default) or "daily"
    mode: "hourly"
    name: Pirate Weather



# https://www.home-assistant.io/integrations/ombi
ombi:
  host: 192.168.10.4
  username: cchiapusio
  api_key: !secret ombi_api_key
  port: 3579
  urlbase: /
  ssl: false

overseerr:
  host: 192.168.10.4
  port: 5055
  api_key: !secret overseerr_api_key
  scan_interval: 600