####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

# https://home-assistant.io/docs/configuration/basic/
homeassistant:
  # Packages
  packages: !include_dir_named packages
#  name: Home
#  latitude: !secret home_lat
#  longitude: !secret home_long
#  elevation: 1227
#  unit_system: imperial
#  time_zone: America/New_York
#  external_url: !secret external_url
#  internal_url: !secret internal_url
  allowlist_external_dirs:
    - /config/faces/
    - /config/www/
  auth_providers:
   - type: legacy_api_password
     api_password: !secret api_password
   - type: trusted_networks
     trusted_networks:
       - 172.17.0.0/16
       - 192.168.10.0/24
   - type: homeassistant
  customize:
    person.chip:
      entity_picture: !secret profile_photo_chip
    person.cindy:
      entity_picture: !secret profile_photo_cindy
    person.tori:
      entity_picture: !secret profile_photo_tori
    binary_sensor.front_door:
      friendly_name: Front Door
    binary_sensor.back_door:
      friendly_name: Back Door


####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

# https://home-assistant.io/components/config/
config:
#default_config:

# https://www.home-assistant.io/integrations/my/
my:

#https://www.home-assistant.io/docs/energy/
energy:

#https://www.home-assistant.io/components/mobile_app/
#mobile_app:

# https://www.home-assistant.io/hassio/
#hassio:

# https://home-assistant.io/components/history/
history:

# https://www.home-assistant.io/integrations/recorder/
recorder:
  db_url: !secret hass_db_string
  purge_keep_days: 15
  commit_interval: 5
  exclude:
    domains:
      - media_player
      - device_tracker
      - automation
      - updater
    entities:
      - sun.sun
    entity_globs:
      - sensor.weather_*
    event_types:
      - call_service
  include:
    domains:
      - switch
      - light
      - sensor
      - binary_sensor
      - calendar
      - person
      - climate
    entities:
      - device_tracker.galaxy_note10 # unifi
      - device_tracker.sm_s908u # Cindys S22 Ultra
      - media_player.living_room_shield
      - media_player.living_room_tv
      - media_player.toris_bedroom_tv
      - media_player.mbr_shield
      - media_player.master_bedroom_tv
      - device_tracker.toris_iphone_2 # unifi
      - device_tracker.sm_n986u # HA App
      - device_tracker.wled_jeep # unifi
      - automation.backdoor_motion_notification

# https://home-assistant.io/components/http/
http:
  # Secrets are defined in the file secrets.yaml
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#  base_url: !secret base_url_secret
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/24
    - 192.168.10.0/24

# https://home-assistant.io/components/logger/
logger:
  default: info
  logs:
    homeassistant.components.notify: debug
#    homeassistant.components.google_assistant: debug
#    homeassistant.core: debug
#    homeassistant.components.zha: debug
#    bellows.zigbee.application: debug
#    bellows.ezsp: debug
#    zigpy: debug
#    zigpy_cc: debug
#    zigpy_deconz.zigbee.application: debug
#    zigpy_deconz.api: debug
#    zigpy_xbee.zigbee.application: debug
#    zigpy_xbee.api: debug
#    zigpy_zigate: debug
#    zigpy_znp: debug
#    zhaquirks: debug
#    homeassistant.components.mqtt: debug
#    homeassistant.components.zha: debug
#    bellows.ezsp: debug
#    bellows.uart: debug
#    zigpy.zdo: debug
#    zigpy.application: debug

#    aiounifi: debug
#    homeassistant.components.unifi: debug
#    homeassistant.components.device_tracker.unifi: debug
#    homeassistant.components.switch.unifi: debug

# https://www.home-assistant.io/integrations/manual
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: '1234'

# https://home-assistant.io/components/sun/
sun:

# https://www.home-assistant.io/components/system_health/
system_health:

####################################################
#                                                  #
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
#                                                  #
####################################################

# https://home-assistant.io/docs/configuration/splitting_configuration/
zone: !include includes/zones.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
script: !include scripts.yaml
automation: !include_dir_merge_list includes/automation
scene: !include_dir_merge_list includes/scene
notify: !include notification.yaml
light: !include lights.yaml
sensor: !include_dir_merge_list includes/sensors
binary_sensor: !include binary_sensor.yaml
media_player: !include media_player.yaml
person: !include includes/person.yaml
switch: !include includes/switch.yaml
input_select: !include includes/inputs/input_select.yaml
input_number: !include includes/inputs/input_number.yaml
#input_boolean: !include includes/inputs/input_boolean.yaml
input_text: !include includes/inputs/input_text.yaml
#image_processing: !include image_processing.yaml
template: !include templates.yaml
alert: !include includes/alerts.yaml
#https://www.home-assistant.io/components/mqtt/
mqtt: !include mqtt.yaml



# https://www.home-assistant.io/integrations/stream
stream:

# https://www.home-assistant.io/integrations/camera/
camera: !include camera.yaml

# https://www.home-assistant.io/integrations/frontend/
frontend: 
#  javascript_version: latest
  themes: !include_dir_merge_named themes

# https://www.home-assistant.io/integrations/cloud/
cloud:

# https://www.home-assistant.io/integrations/backup/
backup:

# https://www.home-assistant.io/integrations/bluetooth/
bluetooth:

# https://www.home-assistant.io/integrations/google_assistant/
google_assistant:
  project_id: home-assistant-integrati-72eed
  service_account: !include home-assistant-integrati-72eed-e13ed1e9b9c9.json
#  api_key: !secret google_assistant_api
  report_state: true
  exposed_domains:
    - switch
    - light
    - cover
    - group
    - scene
    - script
  expose_by_default: true
  
# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# https://www.home-assistant.io/integrations/python_script
python_script:

# Text to speech
# https://www.home-assistant.io/components/tts/  
tts:
  - platform: google_translate
    service_name: google_say

#https://www.home-assistant.io/components/eufy/
#eufy:
#  username: !secret eufy_username
#  password: !secret eufy_password
#  devices:
#    - address: 192.168.10.202
#      access_token: !secret eufy_access_token
#      type: T1201
#      name: Eufy Switch


#https://www.home-assistant.io/components/panel_iframe/
#panel_iframe:
# nodered:
#   title: 'Node-Red'
#   icon: 'mdi:shuffle-variant'
#   url: 'http://192.168.10.4:1880/'
# tasmoadmin:
#   title: 'TasmoAdmin'
#   icon: mdi:lightbulb-on
#   url: http://192.168.10.4:9541

timer:
  alert:
    duration: '00:00:10'
  5m:
    duration: '00:05:00'
  late_tori:
    duration: '00:15:00'

####################################################
#                                                  #
#                   SPEETEST                       #
#                                                  #
####################################################

##
## https://www.home-assistant.io/integrations/calendar.google/
##
#google:
#  client_id: !secret google_oauth_user
#  client_secret: !secret google_oauth_pass

# https://www.home-assistant.io/integrations/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky_api2
    latitude: !secret home_lat
    longitude: !secret home_long

# https://github.com/alexander0042/pirate-weather-ha
# https://pirateweather.net/
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    # Additional optional values:
    latitude: !secret home_lat
    longitude: !secret home_long
#   mode: "hourly" (default) or "daily"
    mode: "hourly"
    name: Pirate Weather

# https://www.home-assistant.io/integrations/spotify/
#spotify:
#  client_id: !secret spotify_client_id
#  client_secret: !secret spotify_client_secret

#zha:
#  zigpy_config:
#    ota:
#      ikea_provider: true
#      ledvance_provider: true
#    network:
#      channel: 15
#      channels: [15, 20, 25]
# Example LL-HLS configuration.yaml entry.

## LL-HLS
#stream:
#  ll_hls: true
#  part_duration: 0.75
#  segment_duration: 6