- platform: deepstack_object
  ip_address: 192.168.10.4
  port: 5000
  timeout: 10
  save_file_folder: /config/www/ds
  always_save_latest_file: true
  save_timestamped_file: true
  targets:
    - target: person
      confidence: 60
    - target: cat
      confidence: 60
    - target: dog
      confidence: 60
  source:
    - entity_id: camera.bi_backdoor

- platform: deepstack_object
  ip_address: 192.168.10.4
  port: 5000
  timeout: 10
  save_file_folder: /config/www/ds
  always_save_latest_file: true
  save_timestamped_file: true
  targets:
    - target: person
      confidence: 60
    - target: cat
      confidence: 40
    - target: dog
      confidence: 40
  source:
    - entity_id: camera.bi_amcrest1

- platform: deepstack_object
  ip_address: 192.168.10.4
  port: 5000
  timeout: 10
  save_file_folder: /config/www/ds
  always_save_latest_file: true
  save_timestamped_file: true
  targets:
    - target: person
      confidence: 60
    - target: cat
      confidence: 60
    - target: dog
      confidence: 60
  source:
    - entity_id: camera.bi_kitchen

- platform: deepstack_object
  ip_address: 192.168.10.4
  port: 5000
  timeout: 10
  save_file_folder: /config/www/ds
  always_save_latest_file: true
  save_timestamped_file: true
  targets:
    - target: person
      confidence: 40
    - target: car
      confidence: 60
    - target: truck
      confidence: 60
    - target: cat
      confidence: 40
    - target: dog
      confidence: 40
  source:
    - entity_id: camera.bi_front_yard

- platform: deepstack_face
  ip_address: 192.168.10.4
  port: 5000
  timeout: 10
  save_file_folder: /config/www/ds
  detect_only: false
  show_boxes: true
  save_timestamped_file: true
  save_faces: true
  save_faces_folder: /config/faces/
  source:
    - entity_id: camera.bi_amcrest1
