- platform: filter
  name: "Smooth Ecobee temp"
  entity_id: sensor.my_ecobee_temperature
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: filter
  name: "Smooth bedroom temp"
  entity_id: sensor.bedroom_temperature
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: filter
  name: washer running filter
  entity_id: sensor.washer_power
  filters: 
    - filter: time_simple_moving_average
      window_size: 00:05:00
