#############################################################
#
# https://www.home-assistant.io/integrations/ps4/
#
#############################################################

- platform: history_stats
  name: Playstation game time today
  entity_id: media_player.playstation_4
  state: 'playing'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'