#- platform: template
#  sensors:
#    window_ps_lower:
#      value_template: "{{  states('sensor.window1_estimated_current') | int +
#                            states('sensor.window2_estimated_current') | int +
#                           states('sensor.window3_estimated_current') | int +
#                           states('sensor.window4_estimated_current') | int +
#                           states('sensor.window5_estimated_current') | int }} "
#      unit_of_measurement: mA
#      friendly_name: Upper Window Current

#- platform: template
#  sensors:
#    window_ps_upper:
#      value_template: "{{  states('sensor.window6_estimated_current') | int +
#                           states('sensor.window7_estimated_current') | int +
#                           states('sensor.window8_estimated_current') | int }} "
#      unit_of_measurement: mA
#      friendly_name: Lower Window Current


- platform: template
  sensors:
    sun_elevation:
      friendly_name: "Sun Elevation"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"

- platform: template
  sensors:
    sun_azimuth:
      friendly_name: "Sun Azimuth"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('sun.sun', 'azimuth') }}"

#- platform: template
#  sensors:
#    tori_work_destination:
#      friendly_name: "Toris work destination"
#      value_template: >
#        {% set x = state_attr('calendar.work_today', 'location') %}
#        {{ x if x is ne '' else '34.9992354775376, -80.85492410370368' }}

- platform: template
  sensors:
    office_cube_temperature:
      friendly_name: "Office Cube Temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ state_attr('sensor.office_cube_action', 'temperature')}}"

- platform: template
  sensors:
    mbr_cube_temperature:
      friendly_name: "MBR Cube Temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ state_attr('sensor.mbr_cube_action', 'temperature')}}"