automation:
##
## Turn off lights at midnight if the TV is off
##
  - alias: turn off living room lights at midnight
    id: 277b1ae2-1b04-4656-8d6c-ce23f7c84ab4
    trigger:
      platform: time
      at: "23:00:00"
    condition:
      - condition: state
        entity_id: media_player.living_room_tv
        state:  'off'
      - condition: state
        entity_id: person.chip
        state: home
    action:
      - service: scene.turn_on
        entity_id: scene.livingroom_dim
      - service: scene.turn_on
        entity_id: scene.dining_room_dim
      - service: switch.turn_off
        entity_id: switch.curio_cabinet_lamp
      - service: timer.start
        data:
          entity_id: timer.5m

##
## Turn off Lights if TV turns off after midnight
##
  - alias: turn off lights when done watching TV
    id: 9608670a-5061-44ca-9827-239f19ba9b23
    trigger:
      platform: state
      entity_id: media_player.living_room_tv
      to: 'off'
    condition:
      condition: and
      conditions:
        - condition: time
          after: "23:00:00"
          before: "05:00:00"
        - condition: state
          entity_id: sun.sun 
          state: below_horizon
    action:
      - service: scene.turn_on
        entity_id: scene.livingroom_dim
      - service: scene.turn_on
        entity_id: scene.dining_room_dim
      - service: scene.turn_on
        entity_id: scene.kitchen_dim
      - service: timer.start
        data:
          entity_id: timer.5m

  - alias: turn off living room lights after timer
    id: 8767441e-27d8-4d10-a652-6651c84041d7
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.5m
    action:
      service: script.turn_on
      entity_id: script.good_night_lights

  - alias: Media player paused/stopped
    id: b239b22a-5bae-4e71-b7cc-99f7c6fecfb2
    trigger:
      - platform: state
        #entity_id: media_player.living_room_shield, media_player.living_room_tv
        entity_id: media_player.living_room_shield
        #from: playing
        to: idle
#      for:
#        seconds: 8
#        seconds: {{ (states('input_number.light_dim_delay')|int) }}
    condition:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: state
        entity_id: calendar.nfl_schedule_green_bay_packers
        state: "off"
    action:
      service: scene.turn_on
      entity_id: scene.livingroom_full

  - alias: Media player playing
    id: b99dc5b6-0243-4407-86df-1eecc1a00ad3
    trigger:
      - platform: state
        entity_id: media_player.living_room_shield
        to: playing
  #      from: idle
    condition:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: state
        entity_id: calendar.nfl_schedule_green_bay_packers
        state: "off"
    action:
      service: scene.turn_on
      entity_id: scene.livingroom_dim

  - alias: Packers Playing
    id: 76271bea-d291-4264-81bc-9fe2fcde508d
    trigger:   
    - platform: state
      entity_id: calendar.green_bay_packers
      to: "on"
    action:
      service: scene.turn_on
      entity_id: scene.packers_playing

  - alias: Packers done Playing
    id: 6404c369-15d4-4450-b6e1-9d114c135482
    trigger:   
    - platform: state
      entity_id: calendar.green_bay_packers
      to: "off"
    action:
      service: scene.turn_on
      entity_id: scene.livingroom_normal

  #- alias: Tori scheduled for work this morning
  #  id: ab5c5a72-3831-44d1-a860-3fc9b23168c5
  #  trigger:
  #    - platform: time_pattern
  #      minutes: '/5'
  #  condition:
  #    condition: and
  #    conditions:
  #      - condition: time
  #        after: "04:30:00"
  #        before: "09:00:00"
  #      - condition: template
  #        value_template: "{{ ((as_timestamp(states.calendar.work_today.attributes.start_time) - as_timestamp(now())) < 2700) and ((as_timestamp(states.calendar.waterbean_today.attributes.start_time) - as_timestamp(now())) > 0)  }}"
  #      - condition: state
  #        entity_id: person.tori
  #        state: home
  #      - condition: template
  #        value_template: '{{ state_attr("sun.sun", "elevation") < 15 }}'
  #      - condition: state
  #        entity_id: switch.hutch_light
  #        state: 'off'
  #  action:
  #    - service: scene.turn_on
  #      entity_id: scene.livingroom_dim
  #    - service: switch.turn_on
  #      entity_id: switch.hutch_light

  #- alias: Tori left for work
  #  id: 7c8d4f4c-d3f2-426e-a321-c0ea3175bee2
  #  trigger:
  #    - platform: state
  #      entity_id: person.tori
  #      from: home
  #  condition:
  #    - condition: time
  #      after: '04:30:00'
  #      before: '09:00:00'
  #  action:
  #    service: homeassistant.turn_off
  #    entity_id:
  #      - switch.hutch_light
  #      - light.living_room_lamp_1
  #      - light.living_room_lamp_2
  #      - light.foyer_lamp

  - alias: turn on candle in the morning
    id: 8d184c18-380b-4d4a-9528-460badcd25d9
    trigger:
      platform: time
      at: "09:00:00"
    action:
      - service: switch.turn_on
        entity_id: switch.candle_light
      - service: light.turn_on
        entity_id: light.crystal_castle_1,light.crystal_castle_2
        data:
          brightness: 40
      - service: select.select_option
        target:
          entity_id: select.crystal_castle_1_preset
        data:
          option: "Purple sweep"
      - service: select.select_option
        target:
          entity_id: select.crystal_castle_2_preset
        data:
          option: "Preset 1"


# turn on hyperion wled lights when TV turns on
#
  - alias: turn on ambilight when TV turns on
    id: 03e16f89-e328-4051-93e4-f7f6fc96003a
    trigger:
      platform: state
      entity_id: media_player.living_room_tv
      to: 'on'
    action:
    - choose:
      - conditions:
        - condition: state
          entity_id: light.lg75_wled
          state: 'off'
        sequence:
        - service: light.turn_on
          data:
            entity_id: light.lg75_wled
            brightness: 255
      - conditions:
        - condition: state
          entity_id: timer.5m
          state: active
        sequence:
        - service: script.turn_on
          entity_id: script.turn_on_house_lights
        - service: timer.cancel
          target:
            entity_id: timer.5m


scene:
  - name: Livingroom_Normal
    entities:
      light.living_room_lamp_1:
        state: on
        brightness: 255
        color_temp: 454
      light.living_room_lamp_2:
        state: on
        brightness: 255
        color_temp: 454
      light.foyer_lamp:
        state: on
        brightness: 255
        color_temp: 454
      switch.willow_tree:
        state: on
      light.crystal_wall:
        state: on
        brightness: 255
  
  - name: Livingroom_Full
    entities:
      light.living_room_lamp_1:
        state: on
        brightness: 255
      light.living_room_lamp_2:
        state: on
        brightness: 255
      light.foyer_lamp:
        state: on
        brightness: 255
      switch.willow_tree:
        state: on
      light.crystal_wall:
        state: on
        brightness: 255
  
  - name: Livingroom_Dim
    entities:
      light.living_room_lamp_1:
        state: on
        brightness: 76
      light.living_room_lamp_2:
        state: on
        brightness: 76
      light.foyer_lamp:
        state: on
        brightness: 76
      switch.willow_tree:
        state: on
      light.crystal_wall:
        state: on
        brightness: 76

  - name: Packers_playing
    entities:
      light.living_room_lamp_1:
        state: on
        brightness: 255
        color_name: green
      light.living_room_lamp_2:
        state: on
        brightness: 255
        xy_color:
        - 0.461
        - 0.502
      light.foyer_lamp:
        state: on
        brightness: 255
        color_name: green  
  
  - name: Livingroom off
    entities:
      light.living_room_lamp_1:
        state: off
      light.living_room_lamp_2:
        state: off
      light.foyer_lamp:
        state: off
      switch.willow_tree:
        state: off
      light.crystal_wall:
        state: off
      light.lg75_wled:
        state: off