automation:
  - alias: bed motion floor light
    id: 094e94c0-c852-4b74-a90f-27d2b4b64045
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.mbr_bed_1_occupancy
        from: 'off'
        to: 'on'
        id: 'motion'
      - platform: state
        entity_id: binary_sensor.mbr_bed_2_occupancy
        from: 'off'
        to: 'on'
        id: 'motion'
      - platform: state
        entity_id: binary_sensor.mbr_bed_1_occupancy
        from: 'on'
        to: 'off'
        id: 'nomotion'
      - platform: state
        entity_id: binary_sensor.mbr_bed_2_occupancy
        from: 'on'
        to: 'off'
        id: 'nomotion'
    condition:
      condition: and
      conditions:
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: motion
          - condition: state
            entity_id: light.bedroom_lamps
            state: 'off'
          - condition: state
            entity_id: sun.sun
            state: 'below_horizon'
          sequence:
          - service: light.turn_on
            entity_id: light.bed_led
            data:
              rgb_color: [255,0,0]
              brightness: 70
        - conditions:
          - condition: trigger
            id: nomotion
          - condition: state
            entity_id: binary_sensor.mbr_bed_1_occupancy
            state: 'off'
          - condition: state
            entity_id: binary_sensor.mbr_bed_2_occupancy
            state: 'off'
          sequence:
          - service: light.turn_off
            entity_id: light.bed_led

  - alias: nebulizer running
    id: 9754e6ba-c1c6-4640-bd7f-c7ab0f749873
    trigger:
      - platform: state
        entity_id: binary_sensor.nebulizer_running
        id: is_off
        to: 'off'
      - platform: state
        entity_id: binary_sensor.nebulizer_running
        id: is_on
        to: 'on'
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: is_on
          sequence:
          - service: switch.turn_on
            entity_id: switch.salt_lamp
        - conditions:
          - condition: trigger
            id: is_off
          sequence:
          - service: switch.turn_off
            entity_id: switch.salt_lamp

  - id: 037edbbf-3951-42a0-aaa1-4bd980950735
    alias: MBR Cube (z2m)
    mode: queued
    description: ''
    use_blueprint:
      path: SirGoodenough/Zigbee2MQTT - Xiaomi Cube Controller.yaml
      input:
        remote: sensor.mbr_cube_action
        doubletap_any:
        - service: scene.turn_on
          target:
            entity_id: scene.mbr_lights_full
          metadata: {}
        flipped90_any:
        - choose:
          - conditions:
            - condition: and
              conditions:
              - condition: state
                entity_id: light.bedroom_lamps
                state: 'off'
              - condition: state
                entity_id: switch.fairy_lights
                state: 'off'
            sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.mbr_lights_on
              metadata: {}
          - conditions:
            - condition: and
              conditions:
              - condition: state
                entity_id: light.bedroom_lamps
                state: 'on'
              - condition: state
                entity_id: switch.fairy_lights
                state: 'on'
            sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.mood_lighting
              metadata: {}
          - conditions:
            - condition: and
              conditions:
              - condition: state
                entity_id: light.bedroom_lamps
                state: 'off'
              - condition: state
                entity_id: switch.fairy_lights
                state: 'on'
            sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.mbr_lights_off
              metadata: {}
          default: []
        rotate_cw_any:
        - service: light.turn_on
          data:
            brightness_step_pct: 10
          target:
            entity_id: light.bedroom_lamps
        rotate_ccw_any:
        - service: light.turn_on
          data:
            brightness_step_pct: -10
          target:
            entity_id: light.bedroom_lamps

binary_sensor:
  - platform: threshold
    entity_id: sensor.zplug3_power
    name: Nebulizer running
    device_class: running
    upper: 10

scene:
  - name: mood lighting
    entities:
      light.bedroom_lamps:
        state: off
      switch.fairy_lights:
        state: on
      light.crystal_castle_1:
        state: on
      light.crystal_castle_2:
        state: on

  - name: restore bedroom lights
    entities:
      light.bedroom_lamps:
        state: on
        color_temp: 326
    
  - name: mbr lights on
    entities:
      light.bedroom_lamps:
        state: on
        color_temp: 326
      switch.fairy_lights:
        state: on
      light.crystal_castle_1:
        state: on
      light.crystal_castle_2:
        state: on

  - name: mbr lights off
    entities:
      light.bedroom_lamps:
        state: off
      switch.fairy_lights:
        state: off
      light.crystal_castle_1:
        state: off
      light.crystal_castle_2:
        state: off

  - name: mbr lights full
    entities:
      light.bedroom_lamps:
        state: on
        color_temp: 326
        white_value: 125
        brightness: 255
      switch.fairy_lights:
        state: on
      light.crystal_castle_1:
        state: on
      light.crystal_castle_2:
        state: on