automation:
  - alias: bed motion floor light
    id: 094e94c0-c852-4b74-a90f-27d2b4b64045
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.mbr_bed_1_occupancy
        from: 'off'
        to: 'on'
        id: 'motion'
      - platform: state
        entity_id: binary_sensor.mbr_bed_2_occupancy
        from: 'off'
        to: 'on'
        id: 'motion'
      - platform: state
        entity_id: binary_sensor.mbr_bed_1_occupancy
        from: 'on'
        to: 'off'
        id: 'nomotion'
      - platform: state
        entity_id: binary_sensor.mbr_bed_2_occupancy
        from: 'on'
        to: 'off'
        id: 'nomotion'
    condition:
      condition: and
      conditions:
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: motion
          - condition: state
            entity_id: light.bedroom_lamps
            state: 'off'
          - condition: state
            entity_id: sun.sun
            state: 'below_horizon'
          sequence:
          - service: light.turn_on
            entity_id: light.bed_led1
            data:
              rgb_color: [255,0,0]
              brightness: 70
          - service: light.turn_on
            entity_id: light.bed_led2
            data:
              rgb_color: [255,0,0]
              brightness: 70
        - conditions:
          - condition: trigger
            id: nomotion
          - condition: state
            entity_id: binary_sensor.mbr_bed_1_occupancy
            state: 'off'
          - condition: state
            entity_id: binary_sensor.mbr_bed_2_occupancy
            state: 'off'
          sequence:
          - service: light.turn_off
            entity_id: light.bed_led1
          - service: light.turn_off
            entity_id: light.bed_led2

  - id: 037edbbf-3951-42a0-aaa1-4bd980950735
    alias: MBR Cube (z2m)
    mode: queued
    description: ''
    use_blueprint:
      path: SirGoodenough/Zigbee2MQTT - Xiaomi Cube Controller.yaml
      input:
        remote: sensor.mbr_cube_action
        doubletap_any:
        - service: scene.turn_on
          target:
            entity_id: scene.mbr_lights_full
          metadata: {}
        flipped90_any:
        - choose:
          - conditions:
            - condition: and
              conditions:
              - condition: state
                entity_id: light.bedroom_lamps
                state: 'off'
              - condition: state
                entity_id: switch.zplug5
                state: 'off'
            sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.mbr_lights_on
              metadata: {}
          - conditions:
            - condition: and
              conditions:
              - condition: state
                entity_id: light.bedroom_lamps
                state: 'on'
              - condition: state
                entity_id: switch.zplug5
                state: 'on'
            sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.mood_lighting
              metadata: {}
          - conditions:
            - condition: and
              conditions:
              - condition: state
                entity_id: light.bedroom_lamps
                state: 'off'
              - condition: state
                entity_id: switch.zplug5
                state: 'on'
            sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.mbr_lights_off
              metadata: {}
          default: []
        rotate_cw_any:
        - service: light.turn_on
          data:
            brightness_step_pct: 15
          target:
            entity_id: light.bedroom_lamps
        rotate_ccw_any:
        - service: light.turn_on
          data:
            brightness_step_pct: -15
          target:
            entity_id: light.bedroom_lamps
        topic: zigbee2mqtt/mbr_cube

  - alias: York Ghost Sale imminent
    id: e33336a5-3634-4d59-a4c7-1d194e0aecc4
    trigger:   
      - platform: calendar
        entity_id: calendar.york_ghost_merchants
        event: start
        offset: -00:05:00
    action:
      - service: scene.create
        data:
          scene_id: york
          snapshot_entities:
          - light.bedroom_lamps
      - service: light.turn_on
        target:
          entity_id: 
            - light.bedroom_lamps
        data:
          transition: 10
          xy_color: [0.216, 0.077] # purple
          brightness: 200
      - delay:
          seconds: 5
#      - service: script.york_ghost_announce
#      - delay:
#          seconds: 5
      - service: scene.turn_on
        entity_id: scene.mood_lighting

  - id: 4ee65efb-36be-4b68-bd8a-4f0a36b2b47c
    alias: bathroom help button
    description: bathroom Call for help buttons
    triggers:
    - domain: mqtt
      device_id: bd17d5ab66306df0c2f795f67b0fe710
      type: action
      subtype: single
      trigger: device
    conditions: []
    actions:
    - action: script.find_and_alert_chip
      data_template:
        where: 'bathroom'

  - id: db7938b2-69f7-4532-8455-d9d4fbfa2255
    alias: bedroom help buttons
    description: bedroom Call for help buttons
    triggers:
    - domain: mqtt
      device_id: 6193cdff805f0c15add25cb700a6303b
      type: action
      subtype: single
      trigger: device
    conditions: []
    actions:
    - action: script.find_and_alert_chip
      data_template:
        where: 'office'

# turn on hyperion wled lights when TV turns on
#
  - alias: master bedroom tv ambilight
    id: cf51de3f-891c-412e-867b-aebdc9fe8d15
    trigger:
      - platform: state
        entity_id: remote.mbr_shield
        to: 'on'
        id: 'to_on'
      - platform: state
        entity_id: remote.mbr_shield
        to: 'off'
        id: 'to_off'
    action:
    - choose:
      - conditions:
        - condition: state
          entity_id: light.mbr_bias
          state: 'off'
        - condition: trigger
          id: 'to_on'
        sequence:
        - service: light.turn_on
          data:
            entity_id: light.mbr_bias
            brightness: 255
      - conditions:
        - condition: trigger
          id: 'to_off'
        sequence:
        - service: light.turn_off
          entity_id: light.mbr_bias

  - alias: closet motion light
    id: cb565aa8-1a4d-4a07-bc37-f3abc97a9560
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.mmwave1_presence
        from: 'off'
        to: 'on'
        id: 'motion'
      - platform: state
        entity_id: binary_sensor.mmwave1_presence
        from: 'on'
        to: 'off'
        for: '00:01:00'
        id: 'nomotion'
    condition:
    - condition: state
      entity_id: binary_sensor.shelly1minig3_dcda0ce6a6ac_input_0_input
      state: 'on'
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: motion
          sequence:
          - service: switch.turn_on
            entity_id: switch.shelly1minig3_dcda0ce6a6ac_switch_0
        - conditions:
          - condition: trigger
            id: nomotion
          sequence:
          - service: switch.turn_off
            entity_id: switch.shelly1minig3_dcda0ce6a6ac_switch_0

  - alias: mbr motion light
    id: 65f2ef96-89ef-4b87-b899-3793dc6d8824
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.mbr_bathroom_motion_occupancy
        from: 'off'
        to: 'on'
        id: 'motion'
      - platform: state
        entity_id: binary_sensor.mbr_bathroom_motion_occupancy
        from: 'on'
        to: 'off'
        for: '00:03:00'
        id: 'nomotion'
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: motion
          sequence:
          - service: switch.turn_on
            entity_id: switch.usb_a
          - service: switch.turn_on
            entity_id: switch.outlet_1
        - conditions:
          - condition: trigger
            id: nomotion
          sequence:
          - service: switch.turn_off
            entity_id: switch.usb_a
          - service: switch.turn_off
            entity_id: switch.outlet_1

scene:
  - name: mood lighting
    entities:
      light.bedroom_lamps:
        state: off
      switch.zplug5:
        state: on
      light.mirror_fairy:
        state: on
      light.crystal_castle_1:
        state: on
      light.crystal_castle_2:
        state: on
      light.vanity_fairy:
        state: on
      light.cinderella:
        state: on
        brightness: 25
      switch.fairy_lights:
        state: on

  - name: restore bedroom lights
    entities:
      light.bedroom_lamps:
        state: on
        color_temp: 326
    
  - name: mbr lights on
    entities:
      light.bedroom_lamps:
        state: on
        color_temp: 326
      switch.zplug5:
        state: on
      light.crystal_castle_1:
        state: on
      light.crystal_castle_2:
        state: on
      light.vanity_fairy:
        state: on
      switch.fairy_lights:
        state: on


  - name: mbr lights off
    entities:
      light.bedroom_lamps:
        state: off
      switch.zplug5:
        state: off
      light.crystal_castle_1:
        state: off
      light.crystal_castle_2:
        state: off
      light.vanity_fairy:
        state: off
      light.mirror_fairy:
        state: off
      switch.fairy_lights:
        state: off

  - name: mbr lights full
    entities:
      light.bedroom_lamps:
        state: on
        color_temp: 326
        white_value: 125
        brightness: 255
      switch.zplug5:
        state: on
      light.crystal_castle_1:
        state: on
      light.crystal_castle_2:
        state: on
      light.vanity_fairy:
        state: on
      switch.fairy_lights:
        state: on

script:
  find_and_alert_chip:
    sequence:
      - service: notify.notify_chip
        data:
          message: "Cindy needs help in the {{ where }}"
          data:
            priority: 1

  turn_on_tea_lights:
    sequence: 
      - service: remote.send_command
        target:
          entity_id: remote.rm3mini3
        data:
          device: tea_light
          command:
            - power on
      - service: remote.send_command
        target:
          entity_id: remote.rm3mini4
        data:
          device: tea_light
          command:
            - power on

  turn_off_tea_lights:
    sequence: 
      - service: remote.send_command
        target:
          entity_id: remote.rm3mini3
        data:
          device: tea_light
          command:
            - power off
      - service: remote.send_command
        target:
          entity_id: remote.rm3mini4
        data:
          device: tea_light
          command:
            - power off

#  york_ghost_announce:
#    sequence:
#    - service: tts.clear_cache
#    - service: media_player.volume_set
#      data_template:
#        entity_id:
#          - media_player.all
#        volume_level: 0.5
#    - service: tts.speak
#      target:
#        entity_id: tts.piper
#      data:
#        cache: true 
#        media_player_entity_id: media_player.all
#        message: "There is a York Ghost Merchant Sale about to begin"
