script:
  learn_string_lights_rf:
    alias: learn string lights rf
    sequence:
      - service: remote.learn_command
        target:
          entity_id: remote.rm4pro_remote
        data:
          device: string_lights
          command_type: rf
          command:
            - turn on
            - turn off
            - 2700k
            - 4000k
            - 5000k
            - percent_25
            - percent_50
            - percent_75
            - percent_100
            - brighter
            - dimmer
            - timer_30
            - timer_60
            - timer_120
            - timer_240

  turn_on_string_lights:
    alias: turn on string lights
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.rm4pro_remote
        data:
          device: string_lights
          command:
            - turn on
            - percent_100
            - 2700k

  turn_off_string_lights:
    alias: turn off string lights
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.rm4pro_remote
        data:
          device: string_lights
          command:
            - turn off

automation:

  - alias: turn on deck floodlights at sunset
    id: d50b3dbe-d917-4aec-8bb9-6b1c4a8d98d9
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -3
      - platform: state
        entity_id: binary_sensor.shellyplus2pm_c4d8d5565bac_input_1_input
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.shellyplus2pm_c4d8d5565bac_input_1_input
          state: 'on'
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: state
          entity_id: sun.sun
          attribute: rising
          state: false
    action:
      - service: homeassistant.turn_on
        entity_id: switch.shellyplus2pm_c4d8d5565bac_switch_1

  - alias: turn on front porch lights 
    id: 9eb378bd-b231-4edf-b857-8a070d08d145
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -3
      - platform: state
        entity_id: binary_sensor.shelly_2_5_8caab55f9707_input_0
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.shelly_2_5_8caab55f9707_input_0
          state: 'on'
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: state
          entity_id: input_select.porch_light_setting
          state: 'always on'
        - condition: state
          entity_id: sun.sun
          attribute: rising
          state: false
    action:
      - service: homeassistant.turn_on
        entity_id: switch.shelly_2_5_8caab55f9707_relay_0
      
  - alias: turn front driveway floods
    id: 7498deb5-bef0-4f96-a5c2-30a9939ba3af
    trigger: 
      - platform: state
        entity_id: binary_sensor.shelly_2_5_8caab55f9707_input_1
        to: 'on'
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -3
      - platform: numeric_state
        entity_id: sensor.shelly_2_5_8caab55f9707_power_1
        below: 10
        for: "00:05:00"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.shelly_2_5_8caab55f9707_input_1
          state: 'on'
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: state
          entity_id: input_select.front_flood_setting
          state: 'always on'
    action:
      - service: homeassistant.turn_on
        target:
          entity_id: switch.shelly_2_5_8caab55f9707_relay_1
      - service: homeassistant.turn_off
        target:
          entity_id: switch.shelly_2_5_8caab55f9707_relay_1
      - delay: 00:00:02
      - service: homeassistant.turn_on
        target:
          entity_id: switch.shelly_2_5_8caab55f9707_relay_1
    
  - alias: turn back driveway floods
    id: e6ffac97-3bcf-483c-b91c-754ac733f26c
    trigger: 
      - platform: state
        entity_id: binary_sensor.shellyplus2pm_c4d8d5565bac_input_0_input
        to: 'on'
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -3
      - platform: numeric_state
        entity_id: sensor.shellyplus2pm_c4d8d5565bac_switch_0_power
        below: 10
        for: "00:05:00"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.shellyplus2pm_c4d8d5565bac_input_0_input
          state: 'on'
        - condition: state
          entity_id: sun.sun
          state: below_horizon
    action:
      - service: homeassistant.turn_on
        target:
          entity_id: switch.shellyplus2pm_c4d8d5565bac_switch_0
      - service: homeassistant.turn_off
        target:
          entity_id: switch.shellyplus2pm_c4d8d5565bac_switch_0
      - delay: 00:00:02
      - service: homeassistant.turn_on
        target:
          entity_id: switch.shellyplus2pm_c4d8d5565bac_switch_0
