##
## Light (groups)
##
light:
  - platform: group
    name: Front Yard Floods
    entities:
      - light.flood04
      - light.flood05
      - light.flood06
      - light.flood08

  - platform: group
    name: Front Yard Island Floods
    entities:
      - light.flood05
      - light.flood06

input_select:
  outdoor_light_scene:
    name: Outdoor Light Scene
    options:
      - Normal
      - Halloween
      - Thanksgiving
      - Christmas
      - Valentines Day
      - St Patricks
      - Easter
      - Independence Day
      - Memorial Day
      - Green Bay Packers
      - Miami Dolphins
    icon: mdi:string-lights

##
## Automations
##

automation:
  - alias: front yard scene
    id: 2dd3178d-2aee-45a8-95b4-a9aa0d8dee0f
    trigger:
      platform: sun
      event: sunset
      offset: "-00:30:00"
    condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'Normal'
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'Halloween'
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'Thanksgiving'
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'Christmas'
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'Valentines Day'
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'St Patricks'
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'Independence Day'
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'Memorial Day'
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'Green Bay Packers'
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'Miami Dolphins'
        - condition: state
          entity_id: 'input_select.outdoor_light_scene'
          state: 'Easter'
    action:
      - service: scene.turn_on
        data_template:
          entity_id: >
            {% if is_state( "input_select.outdoor_light_scene", "Normal" ) %}
              scene.yard_light_normal
            {% elif is_state( "input_select.outdoor_light_scene", "Halloween" ) %}
              scene.yard_light_halloween
            {% elif is_state( "input_select.outdoor_light_scene", "Thanksgiving" ) %}
              scene.yard_light_thanksgiving
            {% elif is_state( "input_select.outdoor_light_scene", "Christmas" ) %}
              scene.yard_light_christmas
            {% elif is_state( "input_select.outdoor_light_scene", "Valentines Day" ) %}
              scene.yard_light_valentines
            {% elif is_state( "input_select.outdoor_light_scene", "St Patricks" ) %}
              scene.yard_light_stpatricks
            {% elif is_state( "input_select.outdoor_light_scene", "Independence Day" ) %}
              scene.yard_light_independence
            {% elif is_state( "input_select.outdoor_light_scene", "Memorial Day" ) %}
              scene.yard_light_independence
            {% elif is_state( "input_select.outdoor_light_scene", "Green Bay Packers" ) %}
              scene.yard_light_greenbay
            {% elif is_state( "input_select.outdoor_light_scene", "Miami Dolphins" ) %}
              scene.yard_light_dolphins
            {% elif is_state( "input_select.outdoor_light_scene", "Easter" ) %}
              scene.yard_light_easter
            {% endif %}

  - alias: floods_off_at_dawn
    id: 1973456b-bc9c-46ec-a5bc-b7daca87c62c
    trigger:
      platform: sun
      event: sunrise
      offset: "-00:00:00"
    action:
      - service: light.turn_off
        entity_id: light.front_yard_floods
      - service: switch.turn_off
        entity_id: switch.outdoor_switch_3_1
      - service: switch.turn_off
        entity_id: switch.outdoor_switch_3_2
      - service: switch.turn_off
        entity_id: switch.outdoor_switch_4_1
      - service: switch.turn_off
        entity_id: switch.outdoor_switch_4_2
      - service: switch.turn_off
        entity_id: switch.outdoor_switch_5_1
      - service: switch.turn_off
        entity_id: switch.outdoor_switch_5_2

  - alias: turn off house floods at midnight
    id: 242a674a-11c6-4896-a34c-ca537dac9f55
    trigger:
      platform: time
      at: "00:00:00"
    action:
      - service: scene.turn_on
        entity_id: scene.yard_light_night


  - alias: plug in front floods after yardwork reminder
    id: 9204945a-8e8e-481b-a092-5542d17f045f
    trigger: 
    - platform: state
      entity_id: light.front_yard_island_floods
      to: 'unavailable'
      for:
        hours: 2
    action:
    - service: notify.mobile_app_chip
      data:
        message: "plug in the Front Yard lights"

##
## Christmas
##
  - alias: turn off christmas lights at midnight
    id: 23306405-9f42-459e-a243-5060ac896827
    trigger:
      platform: time
      at: "00:00:00"
    condition:
      - condition: state
        entity_id: input_select.outdoor_light_scene
        state: 'Christmas'
    action:
      - service: scene.turn_on
        entity_id: scene.yard_lights_night
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_1_1
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_3_1
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_4_1
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_5_1
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_5_2
      - service: switch.turn_off
        entity_id: switch.fairy_lights
      - service: switch.turn_off
        entity_id: switch.skeleton_head
##
## Halloween
##

  - alias: turn off halloween props at midnight
    id: 32f5da5d-86a7-488c-867c-771b27414644
    trigger:
      platform: time
      at: "00:00:00"
    condition:
      - condition: state
        entity_id: input_select.outdoor_light_scene
        state: 'Halloween'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_3_1
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_3_2
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_4_1
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_4_2
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_5_1
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_5_2
      - service: homeassistant.turn_off
        entity_id: switch.head_turner
      - service: script.audio_security_mode

  - alias: turn off halloween props at mid-morning
    id: 2c231044-7687-4945-a9bc-38ce39c88fe9
    trigger:
      platform: time
      at: "09:00:00"
    condition:
      - condition: state
        entity_id: input_select.outdoor_light_scene
        state: 'Halloween'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_3_1
      - service: homeassistant.turn_off
        entity_id: switch.outdoor_switch_5_2

  - alias: turn on halloween props for morning commute
    trigger:
      platform: time
      at: "06:00:00"
    condition:
      - condition: state
        entity_id: input_select.outdoor_light_scene
        state: 'Halloween'
    action:
      - service: switch.turn_on
        entity_id: switch.outdoor_switch_5_2
      - service: switch.turn_on
        entity_id: switch.outdoor_switch_3_1
      - service: homeassistant.turn_on
        entity_id: switch.head_turner
      - delay: 00:00:05
      - service: homeassistant.turn_off
        entity_id: switch.head_turner
      - service: remote.send_command
        target:
          entity_id: remote.rm3mini2
        data:
          device: projector
          command:
            - turn off
      - service: script.audio_work_mode

  - alias: turn on halloween props for early evening
    id: e550221c-3900-41c8-ba82-6375016c67aa
    trigger:
      platform: time
      at: "17:00:00"
    condition:
      - condition: state
        entity_id: input_select.outdoor_light_scene
        state: 'Halloween'
    action:
      - service: switch.turn_on
        entity_id: switch.outdoor_switch_3_1
      - service: switch.turn_on
        entity_id: switch.outdoor_switch_5_2
      - service: homeassistant.turn_on
        entity_id: switch.head_turner


  - alias: turn on projector
    id: 9f3044ac-6a92-4f1d-b201-8150d608c2b9
    trigger:
      platform: sun
      event: sunset
      offset: "+00:30:00"
    condition:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: state
        entity_id: input_select.outdoor_light_scene
        state: 'Halloween'
    action:
      - service: script.start_projector

  - alias: turn off projector
    id: ccb25ca6-f641-46a7-b0b5-63bbe719af02
    trigger:
      platform: time
      at: "06:00:00"
    condition:
      - condition: state
        entity_id: input_select.outdoor_light_scene
        state: 'Halloween'
    action:
      - service: remote.send_command
        target:
          entity_id: remote.rm3mini2
        data:
          device: projector
          command:
            - power toggle

##
## Scenes
##
scene:
  - name: yard_light_normal
    entities:
      light.flood04:
        state: on
        color_temp: 6500
        brightness: 200
      light.flood05:
        state: on
        hs_color: [243, 3]
        brightness: 200
      light.flood06:
        state: on
        hs_color: [243, 3]
        brightness: 200
      light.flood08:
        state: on
        hs_color: [28.391, 65.659]
        brightness: 200

  - name: yard_light_night
    entities:
      light.flood04:
        state: on
        brightness: 25
      light.flood05:
        state: on
        brightness: 25
      light.flood06:
        state: on
        brightness: 25
      light.flood08:
        state: off
      switch.outdoor_switch_1_1:
        state: off
      switch.outdoor_switch_1_2:
        state: off
      switch.outdoor_switch_1_3:
        state: off
      switch.outdoor_switch_3_1:
        state: off
      switch.outdoor_switch_3_2:
        state: off
      switch.outdoor_switch_4_1:
        state: off
      switch.outdoor_switch_4_2:
        state: off
      switch.outdoor_switch_5_1:
        state: off
      switch.outdoor_switch_5_2:
        state: off

  - name: yard_light_halloween
    entities:
      light.flood04:
        state: on
        brightness: 255 
        xy_color: [0.701, 0.299] # red
      light.flood05:
        state: on
        brightness: 255 
        xy_color: [0.136, 0.04] 
      light.flood06:
        state: on
        brightness: 117 
        xy_color: [0.581, 0.245] 
      light.flood08:
        state: on
        brightness: 217 
        xy_color: [0.701, 0.299] # red
      switch.outdoor_switch_1_1:
        state: on
      switch.outdoor_switch_1_2:
        state: on
      switch.outdoor_switch_3_1:
        state: on
      switch.outdoor_switch_3_2:
        state: on
      switch.outdoor_switch_4_1:
        state: on
      switch.outdoor_switch_4_2:
        state: on
      switch.outdoor_switch_5_1:
        state: on
      switch.outdoor_switch_5_2:
        state: on

  - name: yard_light_thanksgiving
    entities:
      light.flood04:
        state: on
        hs_color: [53, 100]
        brightness: 255
      light.flood05:
        state: on
        hs_color: [28, 66]
        brightness: 255
      light.flood06:
        state: on
        hs_color: [2, 100]
        brightness: 255
      light.flood08:
        state: on
        hs_color: [24, 98]
        brightness: 255
      switch.outdoor_switch_5_1:
        state: on
      switch.outdoor_switch_5_2:
        state: on

  - name: yard_light_christmas
    entities:
      light.flood04:
        state: on
        brightness: 255 
        xy_color: [0.701, 0.299] # red
      light.flood05:
        state: on
        brightness: 255 
        xy_color: [0.172, 0.747] # green
      light.flood06:
        state: on
        brightness: 255 
        xy_color: [0.701, 0.299] # red
      light.flood08:
        state: on
        brightness: 255 
        xy_color: [0.172, 0.747] # green
      switch.outdoor_switch_1_1:
        state: on
      switch.outdoor_switch_3_1:
        state: on
      switch.outdoor_switch_4_1:
        state: on
      switch.outdoor_switch_5_1:
        state: on
      switch.outdoor_switch_5_2:
        state: on

  - name: yard_light_valentines
    entities:
      light.flood04:
        state: on
        brightness: 255 
        xy_color: [0.701, 0.299] # red
      light.flood05:
        state: on
        brightness: 255 
        xy_color: [0.701, 0.299] # red
      light.flood06:
        state: on
        brightness: 255 
        xy_color: [0.701, 0.299] # red
      light.flood08:
        state: on
        brightness: 255 
        xy_color: [0.701, 0.299] # red
      switch.outdoor_switch_5_1:
        state: on
      switch.outdoor_switch_5_2:
        state: on

  - name: yard_light_stpatricks
    entities:
      light.flood04:
        state: on
        brightness: 255 
        xy_color: [0.172, 0.747] # green
      light.flood05:
        state: on
        brightness: 255 
        xy_color: [0.172, 0.747] # green
      light.flood06:
        state: on
        brightness: 255 
        xy_color: [0.172, 0.747] # green
      light.flood08:
        state: on
        brightness: 255 
        xy_color: [0.172, 0.747] # green
      switch.outdoor_switch_5_1:
        state: on
      switch.outdoor_switch_5_2:
        state: on

  - name: yard_light_independence
    entities:
      light.flood04:
        state: on
        brightness: 255 
        xy_color: [0.701, 0.299] # red
      light.flood05:
        state: on
        brightness: 255 
        xy_color: [0.701, 0.299] # red
      light.flood06:
        state: on
        brightness: 255 
        xy_color: [0.701, 0.299] # red
      light.flood08:
        state: on
        brightness: 255 
        xy_color: [0.126, 0.04] # blue
      switch.outdoor_switch_5_1:
        state: on
      switch.outdoor_switch_5_2:
        state: on

  - name: yard_light_greenbay
    entities:
      light.flood04:
        state: on
        brightness: 255 
        xy_color: [0.172, 0.747] # green
      light.flood05:
        state: on
        brightness: 255 
        xy_color: [0.172, 0.747] # green
      light.flood06:
        state: on
        brightness: 255 
        xy_color: [0.172, 0.747] # green
      light.flood08:
        state: on
        brightness: 255 
        xy_color: [0.461, 0.502] # Yellow

  - name: yard_light_dolphins
    entities:
      light.flood04:
        state: on
        brightness: 255 
        xy_color: [0.141, 0.137] # Light Blue
      light.flood05:
        state: on
        brightness: 255 
        xy_color: [0.141, 0.137] # Light Blue
      light.flood06:
        state: on
        brightness: 255 
        xy_color: [0.612, 0.374] # Orange-ish
      light.flood08:
        state: on
        brightness: 255 
        xy_color: [0.612, 0.374] # Orange-ish

  - name: yard_light_easter
    entities:
      light.flood04:
        state: on
        color_temp_kelvin: 2700
        brightness: 75
      light.flood05:
        state: on
        xy_color: [0.612, 0.374] # orange-ish
        brightness: 255
      light.flood06:
        state: on
        xy_color: [0.157, 0.05] # blue
        brightness: 255
      light.flood08:
        state: on
        color_temp_kelvin: 2700
        brightness: 75
      switch.outdoor_switch_5_1:
        state: on
      switch.outdoor_switch_5_2:
        state: on

  - name: its_showtime
    entities:
      switch.outdoor_switch_3_1:
        state: on
      switch.outdoor_switch_5_2:
        state: on
      switch.head_turner:
        state: on

  - name: showtime_is_over
    entities:
      switch.outdoor_switch_3_1:
        state: off
      switch.outdoor_switch_5_2:
        state: off
      switch.head_turner:
        state: off
      

script:
  start_projector:
    sequence:
      - service: remote.send_command
        target:
          entity_id: remote.rm3mini2
        data:
          device: projector
          command:
            - power toggle
      - delay: 15
      - service: remote.send_command
        target:
          entity_id: remote.rm3mini2
        data:
          device: projector
          command:
            - select
            - select
            - down
      - delay: 1
      - service: remote.send_command
        target:
          entity_id: remote.rm3mini2
        data:
          device: projector
          command:
            - play